# Site settings
title: Что и как в Чехии
email: info@grechka.cz
description: > # this means to ignore newlines until "baseurl:"
     Что и как в Чехии. Полезные советы, ситуации из жизни, личный опыт.
baseurl: 
url: "http://grechka.cz" # the base hostname & protocol for your site
twitter_username: grechkacz

# Build settings
markdown: kramdown
encoding: utf-8
excerpt_separator: <!--more-->
paginate: 10
